### ISSUE TITLE
Error: Cannot find module '../models/User'

### ISSUE THREAD

**Issue by kaustubherttre** [jaewonhimnae/react-youtube-clone#20]
Require stack:
[0] - /run/media/kaustubh/Data/my-youtube/react-youtube-clone/server/routes/users.js
[0] - /run/media/kaustubh/Data/my-youtube/react-youtube-clone/server/index.js
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:743:27)
[0]     at Module.require (internal/modules/cjs/loader.js:965:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (/run/media/kaustubh/Data/my-youtube/react-youtube-clone/server/routes/users.js:3:18)
[0]     at Module._compile (internal/modules/cjs/loader.js:1076:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[0]     at Module.load (internal/modules/cjs/loader.js:941:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:782:14)
[0]     at Module.require (internal/modules/cjs/loader.js:965:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (/run/media/kaustubh/Data/my-youtube/react-youtube-clone/server/index.js:24:23)
[0]     at Module._compile (internal/modules/cjs/loader.js:1076:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[0]     at Module.load (internal/modules/cjs/loader.js:941:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:782:14) {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]     '/run/media/kaustubh/Data/my-youtube/react-youtube-clone/server/routes/users.js',
[0]     '/run/media/kaustubh/Data/my-youtube/react-youtube-clone/server/index.js'
[0]   ]
[0] }

**Comment by jumpersdevice** [comment]
how did you solve this?

**Comment by jumpersdevice** [comment]
renaming user to User.js looks like it fixed it
