### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by akshaygharde49** [jaewonhimnae/react-youtube-clone#8]
MongoNetworkError: connection 0 to cluster0-shard-00-00-ckcn7.mongodb.net:27017 closed
     at TLSSocket.<anonymous> (C:\Users\akshaygharde\Desktop\react-youtube-clone-master\node_modules\mongodb\lib\core\connection\connection.js:352:9)
     at Object.onceWrapper (events.js:418:26)
     at TLSSocket.emit (events.js:311:20)
     at net.js:668:12
     at TCP.done (_tls_wrap.js:556:7) {
   name: 'MongoNetworkError',
   errorLabels: [ 'TransientTransactionError' ],
   [Symbol(mongoErrorContextSymbol)]: {}
}

**Comment by samirpatel017** [comment]
you can add like this username:password insteaad of username:<password> in dev.js

It's work for me !!
